<?php ob_start(); ?>
<h3>BIENVEVENUE SUR LE SITE DU LYCEE PRIVE MODERNE JOSEPH SOUZA DU GABON (PORT GENTIL)</h3>


<p>
  Situé à PORT GENTIL entre le centre Hospitalier Régional et le marché Moukala, le LYCEE MODERNE MODERNE JOSEPH SOUZA est un établissement secondaire privé d'enseignement général.

  L'objectif principal du site est d'informer sur la vie de notre lycée, d'éclairer le public sur son histoire, ses anciens dirigeants. Nos élèves seront d'avantage informés sur les projets d'établissement du lycée. il s'agit aussi de renseigner les anciens du lycée sur les importants changements opérés dans le lycée depuis leur départ.

  A travers nos différents rubriques et notre galerie photo, vous allez pouvoir visiter notre établissement et deécouvrir les activités pédagogiques ainsi que les évènements organisés au sein du lycée. Les élèves y trouveront également le règlement interieur du lycée, les photos dans anciens élèves, leurs rélevés de notes et bulletins mise en ligne par l'établissement.Les parents d'élèves pourront quant à eux, apprendre d'avantage sur l'établissement fréquenté par leurs enfants et seront aussi informés de l'actualité ou sur ses activités socioculturelles.

                                      Bonne visite à tous!

</p>

<?php $content = ob_get_clean();

include 'template.phtml';