<?php
    if( isset($_SESSION['personne']) )
        header("location: .");
    ob_start();
?>
<h2>Connexion</h2>

<form action="" method="post">

    <div class="form-group">
        <label for="">Login </label>
        <input type="text" name="login" class="form-control" placeholder="Login">
    </div>

    <div class="form-group">
        <label for="">Mot de passe </label>
        <input type="password" name="mdp" class="form-control" placeholder="password">
    </div>

    <input type="submit" class="btn btn-primary" name="connexion">
</form>
     
<?php $content = ob_get_clean();

include 'template.phtml';