<?php ob_start(); ?>
<h2>Inscription</h2>

<form action="" method="post" id="inscription"> 
    <div class="form-group">
        <label for="">Nom </label>
        <input type="text" name="nom" class="form-control" placeholder="Nom" id="nom">
    </div>

    <div class="form-group">
        <label for="">Mail </label>
        <input type="email" name="mail" class="form-control" placeholder="Mail" id="mail">
    </div>

    <div class="form-group">
        <label for="">Login </label>
        <input type="text" name="login" class="form-control" placeholder="Login" id="login">
    </div>

    <div class="form-group">
         <label for="">Mot de passe </label>
         <input type="password" name="mdp" class="form-control" placeholder="password" id="mdp1">
    </div>

    <div class="form-group">
         <label for="">Confirmer mot de passe </label>
          <input type="password" name="confirm" class="form-control" placeholder="confirm password" id="mdp2">
   </div>  

<p style="color: red;" id="erreur"></p>
        <input type="submit" class="btn btn-primary" name="inscription">
</form>

<?php $content = ob_get_clean();

include 'template.phtml';