<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="publique/css/style.css">
  <title>LYCEE SOUZA</title>
</head>
<body>
    <header class="jumbotron" style="background-color: #f8fcfd">
		<div class="text-center">
            <a href=".">
                <img src="publique/image/logo1.jpg." alt="logo" style="width: 8%"   class="img-fluid" >
            </a>
            <h1 class="font-weight-bold"> 
                <marquee>Bienvenue au lycee prive moderne joseph souza (Gabon)</marquee>
            </h1>
        </div>
        <nav class="d-flex justify-content-around">
            <?php if(isset($_SESSION['personne'])): ?>
                <?php if( unserialize($_SESSION['personne'])->getStatut() == 'personnel' ): ?>
                    <a href="?action=ajouter">Ajouter</a>
                    <a href="?action=deposer">Déposer</a>
                    <a href="?action=deconnexion">Déconnexion</a>
                <?php endif; ?>
                <?php if( unserialize($_SESSION['personne'])->getStatut() == 'eleve' ): ?>
                    <a href="?action=consulter">Consulter</a>
                    <a href="?action=reglement">Reglement</a>
                    <a href="?action=photos">Phtos</a>
                    <a href="?action=telecharger">Telecharger</a>	
                    <a href="?action=deconnexion">Déconnexion</a>
                <?php endif; ?>   
            <?php else: ?>
                <a href="?action=accueil" class="btn btn-primary mt-1">Accueil</a>
                <a href="?action=inscription" class="btn-primary mt-1">Incription</a>
                <a href="?action=connexion" class="btn btn-primary mt-1">Connexion</a>
            <?php endif; ?>
        </nav>
    </header>

    <main class="container-fluid mb-3">
        <?=  $content ?? "" ?>
    </main>

    <footer>
    	<p class="text-center">
            Suivez-nous sur faceebok: 
            <a href="http://www.facebook/pages/LycéeModerneJoseph Souza-Port-Gentil/238009982964688" target="blank
            ">
                http://www.facebook/pages/Lycée Moderne Joseph Souza-Port-Gentil/238009982964688
            </a>
    	</p>
    </footer>
    <!-- <script src="js/validationform.js"></script> -->

</body>
</html>